# Generated by Django 4.0.6 on 2024-06-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0006_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='Director',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='Genero',
            new_name='genero',
        ),
    ]
