# Generated by Django 4.0.6 on 2024-06-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0008_genero_foto_pelicula_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='generos'),
        ),
    ]
