# Generated by Django 4.0.6 on 2024-06-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0011_alter_director_fotografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='fotografia',
            new_name='foto_dir',
        ),
    ]
